---
- name: Updating sshd configuration
  template: src=sshd_config.j2
            dest=/etc/ssh/sshd_config
            backup=yes
            owner=0 group=0 mode=0644
            validate='/usr/sbin/sshd -T -f %s'
  remote_user: "{{ user }}"
  become: yes
  become_user: root

- name: Restarting ssh service
  service: name=ssh state=restarted
  remote_user: "{{ user }}"
  become: yes
  become_user: root
