---
- name: Creating iptables rules
  template: src=iptables-v4.j2 dest=/tmp/iptables-v4
  remote_user: "{{ user }}"
  become: yes
  become_user: root

- name: Importing the IP v4 iptables rulesets into immediate use
  shell: iptables-restore < /tmp/iptables-v4
  remote_user: "{{ user }}"
  become: yes
  become_user: root

- name: Preventing the iptables-peristent install dialog
  debconf: name=iptables-persistent question={{ item }} vtype=boolean value=true
  with_items:
    - iptables-persistent/autosave_v4
    - iptables-persistent/autosave_v6
  remote_user: "{{ user }}"
  become: yes
  become_user: root

- name: Installing iptables-persistent
  apt: name=iptables-persistent
  remote_user: "{{ user }}"
  become: yes
  become_user: root

- name: Persisting iptables
  service: name=iptables-persistent state=restarted
  remote_user: "{{ user }}"
  become: yes
  become_user: root

- name: Removing the iptables rules
  file: path=/tmp/iptables-v4 state=absent
  remote_user: "{{ user }}"
  become: yes
  become_user: root

- name: Remedying slow apt-get update
  lineinfile: dest=/etc/gai.conf regexp="#precedence ::ffff:0:0/96" line="precedence ::ffff:0:0/96  100"
  remote_user: "{{ user }}"
  become: yes
  become_user: root
