---
- name: Creating the logs folder
  file: path={{ logs_dir }} state=directory
  remote_user: "{{ user }}"

- name: Updating log4j2 cluster configuration
  template: src=cluster.xml.j2
            dest={{ log4j2_dir }}/cluster.xml
  remote_user: "{{ user }}"

- name: Updating log4j2 worker configuration
  template: src=worker.xml.j2
            dest={{ log4j2_dir }}/worker.xml
  remote_user: "{{ user }}"
